# Usa la imagen oficial de MySQL
FROM mysql:8.0.40

# Establece variables de entorno (opcional, pero mejor en docker-compose.yml)
ENV MYSQL_ROOT_PASSWORD 123
ENV MYSQL_DATABASE db
ENV MYSQL_USER root
ENV MYSQL_PASSWORD 123

# Expone el puerto de MySQL
EXPOSE 3306